server:
  port: 8082

spring:
  application:
    name: Notification
  datasource:
    password: abc123
    url: jdbc:postgresql://192.168.182.128:5432/notification
    username: esekelvin
  zipkin:
    base-url: http://192.168.182.128:9411
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enable: true