services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
   # environment:
     # - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
     # - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    #depends_on:
    #  - storage


  #Postgress database for Customer Microservice
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: esekelvin
      POSTGRES_PASSWORD: abc123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  #Postgress database for Fraud Microservice
  postgres_fraud:
    container_name: postgres_fraud
    image: postgres
    environment:
      POSTGRES_USER: esekelvin
      POSTGRES_PASSWORD: abc123
      PGDATA: /data/postgres
    volumes:
      - postgres_fraud:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  #pg admin container setup
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
#creating docker network
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  postgres_fraud:


